### ISSUE TITLE
Game install

### ISSUE THREAD

**Issue by dmitrytrager** [joeyschoblaska/rails5chess#3]
Where is [this method](https://github.com/joeyschoblaska/rails5chess/blob/master/app/assets/javascripts/channels/game.coffee#L4) defined?

**Comment by schoblaska** [comment]
Good catch... it's not! I used to send moves from the board to the subscription via a `made_move` event, which I registered in that `@install` function. When I was doing the writeup though, I realized that I could send the moves to the subscription via the global `App.game`, and it would be one less thing to explain: https://github.com/joeyschoblaska/rails5chess/commit/e169bb1087d78001198a7c6ed75f8459d0491250

I'll remove the call to this old function. Thanks for finding it!

**Comment by schoblaska** [comment]
https://github.com/joeyschoblaska/rails5chess/commit/e1cac079eb273a2b147dcf0d84eac4b0b5017aab

**Comment by dmitrytrager** [comment]
sure
